name: ESLint Check

on: 
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
    - dev
  push:
jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Set up Node.js environment
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        
    - name: Install frontend dependencies
      working-directory: mern/client
      run: npm install
      
    - name: Install backend dependencies
      working-directory: mern/server
      run: npm install

    - name: Run frontend ESLint
      working-directory: mern/client
      run: npx eslint .

    - name: Run backend ESLint
      working-directory: mern/server
      run: npx eslint .