name: ESLint Check

on: 
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
    - dev
  push:

jobs:
  lint-for-frontend:
    if: |
      (github.event_name == 'pull_request' && contains(github.event.pull_request.changed_files, 'mern/client/')) || 
      (github.event_name == 'push' && contains(github.event.head_commit.modified, 'mern/client/'))
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Set up Node.js environment
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        
    - name: Install frontend dependencies
      working-directory: mern/client
      run: npm install
      
    - name: Run frontend ESLint
      working-directory: mern/client
      run: npx eslint . --fix
      continue-on-error: true
  
  lint-for-backend:
    if: |
      (github.event_name == 'pull_request' && contains(github.event.pull_request.changed_files, 'mern/server/')) || 
      (github.event_name == 'push' && contains(github.event.head_commit.modified, 'mern/server/'))
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set up Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      
      - name: Install backend dependencies
        working-directory: mern/server
        run: npm install

      - name: Run backend ESLint
        working-directory: mern/server
        run: npx eslint . --fix
        continue-on-error: true