name: ESLint Check

on: 
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
    - dev
  push:
jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up Node.js environment
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
    - name: Install dependencies
      run: npm install